# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasemanager', '0003_auto_20190605_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('unit', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
