# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasemanager', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='atoll',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
